cinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),

]


if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path, include
from . import views
from . import models


urlpatterns = [
    path('', views.index_page, name='home'),
    path('watching_a_movie <name>', views.player_page, name='watching_a_movie'),
    path('detailed_description <name>', views.about_page, name='подробнее'),
    path('films', views.films_page, name='films'),
    path('films_comedy', views.films_comedy_page, name='films_comedy'),
    path('films_drama', views.films_drama_page, name='films_drama'),
    path('films_horror', views.films_horror_page, name='films_horror'),
    path('films_romance', views.films_romance_page, name='films_romance'),
    path('series_comedy', views.series_comedy_page, name='series_comedy'),
    path('series_drama', views.series_drama_page, name='series_drama'),
    path('series_horror', views.series_horror_page, name='series_horror'),
    path('series_romance', views.series_romance_page, name='series_romance'),
    path('cartoons_mystery', views.cartoons_mystery_page, name='cartoons_mystery'),
    path('cartoons_anime', views.cartoons_anime_page, name='anime_drama'),
    path('cartoons_science_fiction', views.cartoons_science_fiction_page, name='cartoons_science_fiction'),
    path('series', views.series_page, name='series'),
    path('cartoons', views.cartoons_page, name='cartoons'),
    path('admin', views.admin, name='admin'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    # path("about_actor <name>", views.ActorView.as_view(), name="actor_detail"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
    path("director/<str:slug>/", views.DirectorView.as_view(), name="director_detail"),

    path("search", views.Search.as_view(), name='search'),

]

movies/models.py
from django.db import models
from django.urls import reverse


class Actor(models.Model):
    """Актеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to='actors')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры"
        verbose_name_plural = "Актеры"


class Director(models.Model):
    """режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to='actors')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('director_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Режиссеры"
        verbose_name_plural = "Режиссеры"


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    # description = models.TextField("Описание")
    # url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Genre(models.Model):
    """Жанры"""
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категория")
    name = models.CharField("Название жанра", max_length=100)

    def __str__(self):
        return f"{self.categories} - {self.name}"

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    name = models.CharField("Название фильма", max_length=100)
    description = models.TextField("Описание", max_length=5000)
    image = models.ImageField("Изображение", upload_to='movie')

    category = models.ManyToManyField(Actor, verbose_name="Категория фильма", related_name="category")
        # = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категории")

    films = models.BooleanField("Фильм", default=False, help_text="Выберите жанр фильма, который добавляете на сайт")
    films_comedy = models.BooleanField("Жанр - комедия", default=False)
    films_drama = models.BooleanField("Жанр - драма", default=False)
    films_horror = models.BooleanField("Жанр - ужасы", default=False)
    films_romance = models.BooleanField("Жанр - мелодрамма", default=False)

    series = models.BooleanField("Сериал", default=False, help_text="Выберите жанр сериала, который добавляете на сайт")
    series_comedy = models.BooleanField("Жанр - комедия", default=False)
    series_drama = models.BooleanField("Жанр - драма", default=False)
    series_horror = models.BooleanField("Жанр - ужасы", default=False)
    series_romance = models.BooleanField("Жанр - мелодрамма", default=False)
    cartoons = models.BooleanField("Мультфильм", default=False, help_text="Выберите жанр мультфильма,"
                                                                          " который добавляете на сайт")
    mystery = models.BooleanField("Жанр - мистика", default=False)
    science_fiction = models.BooleanField("Жанр - фантастика", default=False)
    anime = models.BooleanField("Жанр - аниме", default=False)
    magnet_link = models.TextField("Введите магнет ссылку", default=False)
    year = models.IntegerField("Введите год премьеры", null=False)
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    director = models.ManyToManyField(Director, verbose_name="режисеры", related_name="film_director")

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'фильмы'

    def __str__(self):
        return self.name


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Название фильма", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots")
    # movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

"""
class MovieShots(models.Model):
    Кадры из фильма
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"
"""


"""
class Reviews(models.Model):
    Отзывы
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
"""

movies/forms.py
from django import forms
"""from snowpenguin.django.recaptcha3.fields import ReCaptchaField"""

from .models import Rating, RatingStar #Reviews,
from django.db import models

"""
class ReviewForm(forms.ModelForm):
    Форма отзывов
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }
"""


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound
from django.views.generic import ListView, DetailView
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

from django.views.generic.base import View
from .forms import RatingForm, Rating


from django.http import HttpResponse
from .models import Movie, MovieShots, Actor, Director, Category, Genre


def category(request):
    return {"category_list": Category.objects.all()}


def index_page(request):
    movies = Movie.objects.all().order_by('-year')
    # movie_stars = Rating.objects.all().order_by('ip')
    return render(request, 'movies/index.html', {'movies': movies})  # 'movie_stars' : movie_stars})


def player_page(request, name):
    movie = Movie.objects.get(name=name)
    magnet_link = movie.magnet_link
    return render(request, 'movies/torrent.html', {'magnet_link': magnet_link})


def about_page(request, name):
    try:
        movie = Movie.objects.get(name=name)
    except ObjectDoesNotExist:
        return HttpResponse("Фильм не найден")
    movie_shots = MovieShots.objects.filter(title=name)
    # убрать потом
    # movie_stars = Rating.objects.all()  # filter(movie__exact=name)
#    list = ['films_comedy', 'films_drama', 'films_horror', 'films_romance']
 #   shots = Movie.objects.get(list=True)
#    print("Shots: ", shots)
    return render(request, 'movies/about.html', {'movie': movie, 'movie_shots': movie_shots})


#def get(slug):

 #   return genres

def films_page(request):
    movies = Movie.objects.filter(films=True).order_by('-year')

    genres = Genre.objects.all()   # selected_related().filter(categories=cat)
    # filter(title__icontains=self.request.GET.get("q"))


        # all()  # filter(categories='films')  # filter(categories='films')
    return render(request, 'movies/films.html', {'movies': movies, 'genres': genres})


class Search(ListView):
    """Поиск фильмов"""
    paginate_by = 3  # выводим 3 фильма

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    """
    __icontains - для того чтобы не учитывался регистр
    self.request.GET.get("q") - значение которое ввел пользователь (имя фильма)
    """

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'   # добавляем в наш словарь
        return context


def films_comedy_page(request):
    movies = Movie.objects.filter(films_comedy=True).order_by('-year')
    return render(request, 'movies/films_comedy.html', {'movies': movies})


def films_drama_page(request):
    movies = Movie.objects.filter(films_drama=True).order_by('-year')
    return render(request, 'movies/films_drama.html', {'movies': movies})


def films_horror_page(request):
    movies = Movie.objects.filter(films_horror=True).order_by('year')
    return render(request, 'movies/films_horror.html', {'movies' : movies})


def films_romance_page(request):
    movies = Movie.objects.filter(films_romance=True)
    return render(request, 'movies/films_romance.html', {'movies' : movies})


def series_page(request):
    movies = Movie.objects.filter(series=True)
    genres = Genre.objects.all()
    return render(request, 'movies/series.html', {'movies': movies, 'genres': genres})


def series_comedy_page(request):
    movies = Movie.objects.filter(series_comedy=True).order_by('year')
    return render(request, 'movies/series_comedy.html', {'movies': movies})


def series_drama_page(request):
    movies = Movie.objects.filter(series_drama=True).order_by('year')
    return render(request, 'movies/series_drama.html', {'movies': movies})


def series_horror_page(request):
    movies = Movie.objects.filter(series_horror=True).order_by('year')
    return render(request, 'movies/series_horror.html', {'movies': movies})


def series_romance_page(request):
    movies = Movie.objects.filter(series_romance=True).order_by('year')
    return render(request, 'movies/series_romance.html', {'movies': movies})


def cartoons_page(request):
    movies = Movie.objects.filter(cartoons=True).order_by('year')
    genres = Genre.objects.all()
    return render(request, 'movies/cartoons.html', {'movies': movies, 'genres': genres})


def cartoons_science_fiction_page(request):
    movies = Movie.objects.filter(science_fiction=True).order_by('year')
    return render(request, 'movies/cartoons_science_fiction.html', {'movies': movies})


def cartoons_mystery_page(request):
    movies = Movie.objects.filter(mystery=True).order_by('year')
    return render(request, 'movies/cartoons_mystery.html', {'movies': movies})


def cartoons_anime_page(request):
    movies = Movie.objects.filter(anime=True).order_by('year')
    return render(request, 'movies/cartoons_anime.html', {'movies': movies})


def admin(request):
    return render(request, 'movies/admin.html')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class ActorView(DetailView):
    """Вывод информации о актере"""
    model = Actor
    template_name = 'movies/about_actor.html'
    slug_field = "name"


class DirectorView(DetailView):
    model = Director
    template_name = 'movies/about_director.html'
    slug_field = "name"


class CategoryView(DetailView):
    model = Category
    template_name = 'movies/<str:slug>/.html'
    slug_field = "name"



"""    Измениния   """
"""
class AddReview(View):
Отзывы

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())
"""

class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

templates/movies/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{movie.name}}</h1>
<div class="left-ads-display col-lg-8">
        <div class="row">
           <div class="desc1-left col-md-6">
{% if movie_shots %}

 <style>
 * {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 2000px;
  max-height: 2000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #ecce80;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #c67f16;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 5s;
  animation-name: fade;
  animation-duration: 5s;
}

@-webkit-keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}


.customers-wrap {
margin-bottom: 90px;
}
.customers-wrap::after {
content: '';
display: table;
clear: both;
}
.customers-block {
display: inline-block;
text-align: center;
width: 25%;
float: left;
}
.customers-img {
width: 261px;
height: 261px;
margin-bottom: 25px;
float: left;
}

  </style>
 <!-- Здесь содержится весь отображаемый контент: -->
  <body>
<div class="slideshow-container">
<!---  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->

<div class="mySlides fade">
  <!--<div class="numbertext">3 / 3</div>-->
  <img src="media/{{movie.image}}" style="width:100%">
  <div class="text"><h1>{{movie.name}}</h1></div>
</div>


{% for movie_shot in movie_shots %}
<div class="mySlides fade">
  <!--<div class="numbertext">3 / 3</div>-->
  <img src="media/{{movie_shot.image}}" style="width:100%">
    <div class="text"><h1> <font color='blue' >{{movie_shot.description}}</font></h1></div>
</div>
{% endfor %}




</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
    {% for movie_shot in movie_shots %}
  <span class="dot"></span>
    {% endfor %}
</div>
<script>
var slideIndex = 0;
var i;
var slides = document.getElementsByClassName("mySlides");
var dots = document.getElementsByClassName("dot");
showSlides();

function showSlides()
{
      for (i = 0; i < slides.length; i++)
      {
        slides[i].style.display = "none";
      }
      slideIndex++;
      if (slideIndex > slides.length)
      {
        slideIndex = 1
      }
      for (i = 0; i < dots.length; i++)
      {
        dots[i].className = dots[i].className.replace(" active", "");
      }

          slides[slideIndex-1].style.display = "block";
          dots[slideIndex-1].className += " active";
          setTimeout(showSlides, 5000); // Change image every 5 seconds
}
</script>


{% else %}
<img src="media/{{movie.image}}" class="img-fluid" alt="">
{% endif %}
           </div>

            <div class="desc1-right col-md-6 pl-lg-4">
                <!--<h3 class="editContent">
                    {{ movie.name }}
                </h3>-->
                <h5 class="editContent" align="left"></h5>
                <p align="left">


                        <span> <p align="left"> <b>
                            Год:</b> {{ movie.year }}
                        </p></span>

                    <li style="list-style: none">
                        <span> <p align="left"> <b>Страна:</b>

                        </p></span>
                    </li>
                    <li style="list-style: none">
                        <span> <p align="left"> <b>Режиссер:</b>
                         {% for director in movie.director.all %}
                        <a href="{{director.get_absolute_url}}">
                                    {{ director.name }}
                            </a>
                        {% endfor %}
                        </p>
                        </span>
                    </li>
                    <li style="list-style: none"><span> <p align="left"> <b>Актеры (в главных ролях):</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{actor.get_absolute_url}}">
                                    {{ actor.name }}
                            </a>
                        {% endfor %}

                    </p></span>
                    </li>
                    <li style="list-style: none"><span>
                        <p align="left">
                        <b>Жанр:</b>
                        </p>

                                    </span>
                    </li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <p align="left">
                            <b>Рейтинг:</b>
                            {% csrf_token %}

                            <input type="hidden" value="{{ movie.ip }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>




                            <span class="editContent">4.0</span>
                            </p>
                        </form>
                    </li>

                </p>
<div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                <p align="centre">
                О фильме
                </p>
            </h3>
            <!--
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            -->
            <p class="editContent" align="justify">
                {{ movie.description|safe }}
            </p>
        </div>



<h1></h1>
<a href="watching_a_movie {{movie.name}}">Перейти к просмотру</a>>

{% endblock %}

templates/movies/about_actor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>  Hello </h1>



<h1>{{ actor.name }} </h1>
    <div class="container py-md-3">
    <div class="side-bar col-lg-4">

    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>



{% endblock %}

templates/movies/about_director.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>  Hello </h1>



<h1>{{ director.name }} </h1>
    <div class="container py-md-3">



    <div class="side-bar col-lg-4">



    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.director}}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ director.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ director.name }}
            </h3>
            <p class="editContent">
                {{ director.description|safe }}
            </p>
        </div>
    </div>



{% endblock %}

templates/movies/cartoons_anime.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
Мультфильмы - аниме
{% endblock %}

{% block content %}
    <h1>Мультфильмы - аниме</h1>


{% for movie in movies %}

<h3>{{ movie.name }}</h3>
<img src="media/{{movie.image}}">
<p>{{ movie.description  }}</p>
<a href="detailed_description {{movie.name}}">Подробнее</a>>
<hr>


<!-- jQuery -->
<script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Bootstrap -->
<script src="/examples/vendors/bootstrap-3.3.7/js/bootstrap.min.js"></script>

{% endfor %}


{% endblock %}

templates/movies/cartoons_mystery.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
Мультфильмы в жанре мистика
{% endblock %}

{% block content %}

    <h1>Мультфильмы в жанре мистика </h1>


{% for movie in movies %}

<h3>{{ movie.name }}</h3>
<img src="media/{{movie.image}}">
<p>{{ movie.description  }}</p>
<a href="detailed_description {{movie.name}}">Подробнее</a>>
<hr>


<!-- jQuery -->
<script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Bootstrap -->
<script src="/examples/vendors/bootstrap-3.3.7/js/bootstrap.min.js"></script>

{% endfor %}

{% endblock %}

templates/movies/cartoons_science_fiction.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
Мультфильмы в жанре фантастика
{% endblock %}

{% block content %}


    <h1>Мультфильмы в жанре фантастика </h1>

{% for movie in movies %}
<h3>{{ movie.name }}</h3>
<img src="media/{{movie.image}}">
<p>{{ movie.description  }}</p>
<a href="detailed_description {{movie.name}}">Подробнее</a>>
<hr>


<!-- jQuery -->
<script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Bootstrap -->
<script src="/examples/vendors/bootstrap-3.3.7/js/bootstrap.min.js"></script>

{% endfor %}


{% endblock %}

templates/movies/films_comedy.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
Фильмы - комедии
{% endblock %}

{% block content %}

    <h1>Фильмы - комедии </h1>
    <p>QQQQ</p>


{% for movie in movies %}
<h3>{{ movie.name }}</h3>
<img src="media/{{movie.image}}">
<p>{{ movie.description  }}</p>
<a href="detailed_description {{movie.name}}">Подробнее</a>>
<hr>


<!-- jQuery -->
<script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Bootstrap -->
<script src="/examples/vendors/bootstrap-3.3.7/js/bootstrap.min.js"></script>

{% endfor %}

{% endblock %}

templates/movies/films_horror.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
Фильмы - ужасы
{% endblock %}

{% block content %}

    <h1> Фильмы - ужасы</h1>
    <p>QQQQ</p>

{% for movie in movies %}

<h3>{{ movie.name }}</h3>
<img src="media/{{movie.image}}">
<p>{{ movie.description  }}</p>
<a href="detailed_description {{movie.name}}">Подробнее</a>>
<hr>


<!-- jQuery -->
<script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Bootstrap -->
<script src="/examples/vendors/bootstrap-3.3.7/js/bootstrap.min.js"></script>

{% endfor %}


{% endblock %}